/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package footballclubmanagement;

import java.util.List;

/**
 *
 * @author LENOVO
 */
public class CoachPage extends javax.swing.JFrame {

    /**
     * Creates new form CoachPage
     */
    public CoachPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MakeAnnouncement = new javax.swing.JButton();
        PlayerInformation = new javax.swing.JButton();
        MakeRequest = new javax.swing.JButton();
        CoachInformation = new javax.swing.JButton();
        ViewAnnouncement = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 0, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/footballclubmanagement/coach (1).png"))); // NOI18N
        jLabel1.setText("   COACH PAGE");

        MakeAnnouncement.setBackground(new java.awt.Color(51, 51, 255));
        MakeAnnouncement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MakeAnnouncement.setForeground(new java.awt.Color(0, 0, 0));
        MakeAnnouncement.setText("Make Announcement");
        MakeAnnouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeAnnouncementActionPerformed(evt);
            }
        });

        PlayerInformation.setBackground(new java.awt.Color(51, 51, 255));
        PlayerInformation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlayerInformation.setForeground(new java.awt.Color(0, 0, 0));
        PlayerInformation.setText("Player Information");
        PlayerInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerInformationActionPerformed(evt);
            }
        });

        MakeRequest.setBackground(new java.awt.Color(51, 51, 255));
        MakeRequest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MakeRequest.setForeground(new java.awt.Color(0, 0, 0));
        MakeRequest.setText("Make Request");
        MakeRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeRequestActionPerformed(evt);
            }
        });

        CoachInformation.setBackground(new java.awt.Color(51, 51, 255));
        CoachInformation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CoachInformation.setForeground(new java.awt.Color(0, 0, 0));
        CoachInformation.setText("Coach Information");
        CoachInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachInformationActionPerformed(evt);
            }
        });

        ViewAnnouncement.setBackground(new java.awt.Color(51, 51, 255));
        ViewAnnouncement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewAnnouncement.setForeground(new java.awt.Color(0, 0, 0));
        ViewAnnouncement.setText("View Announcement");
        ViewAnnouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAnnouncementActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(102, 102, 255));
        close.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Exit");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CoachInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PlayerInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MakeRequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MakeAnnouncement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(CoachInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PlayerInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ViewAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(MakeRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(MakeAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MakeAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeAnnouncementActionPerformed
        // TODO add your handling code here:
        MakeAnnouncement makeann = new MakeAnnouncement();
        makeann.show();
    }//GEN-LAST:event_MakeAnnouncementActionPerformed

    private void ViewAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAnnouncementActionPerformed
        // TODO add your handling code here:
        List<Announcement> ann = FootballClubManagement.readAnnouncements();

        ViewAll viewAnn = new ViewAll();
        viewAnn.setAnnouncements(ann);

        viewAnn.show();
    }//GEN-LAST:event_ViewAnnouncementActionPerformed

    private void PlayerInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerInformationActionPerformed
        // TODO add your handling code here:
        List<Player> p = FootballClubManagement.readPlayer();
        ViewAll viewP = new ViewAll();
        viewP.setPlayerLimitedInfo(p);
        viewP.show();
    }//GEN-LAST:event_PlayerInformationActionPerformed

    private void CoachInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachInformationActionPerformed
        // TODO add your handling code here:
        List<Coach> c = FootballClubManagement.readCoach();
        ViewAll viewC = new ViewAll();
        viewC.setCoachInfo(c);
        viewC.show();
    }//GEN-LAST:event_CoachInformationActionPerformed

    private void MakeRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeRequestActionPerformed
        // TODO add your handling code here:
        CoachRequests cr = new CoachRequests();
        cr.show();
    }//GEN-LAST:event_MakeRequestActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoachPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoachPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoachPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoachPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoachPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CoachInformation;
    private javax.swing.JButton MakeAnnouncement;
    private javax.swing.JButton MakeRequest;
    private javax.swing.JButton PlayerInformation;
    private javax.swing.JButton ViewAnnouncement;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
