/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package footballclubmanagement;

import java.util.List;

/**
 *
 * @author Sabit
 */
public class ManagerPage extends javax.swing.JFrame {

    /**
     * Creates new form ManagerPage
     */
    public ManagerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewAnn = new javax.swing.JButton();
        makeAnn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        playerInfoUpdate = new javax.swing.JButton();
        coachInfoUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        hireCoach = new javax.swing.JButton();
        hirePlayer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        viewFinances = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        viewCoach = new javax.swing.JButton();
        viewPlayers = new javax.swing.JButton();
        coachRequestButton = new javax.swing.JButton();
        playerRequestButton = new javax.swing.JButton();

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Coach Contract Update");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manager Page");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Announcements :");

        viewAnn.setBackground(new java.awt.Color(51, 51, 51));
        viewAnn.setForeground(new java.awt.Color(255, 255, 255));
        viewAnn.setText("View Announcements");
        viewAnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnnActionPerformed(evt);
            }
        });

        makeAnn.setBackground(new java.awt.Color(51, 51, 51));
        makeAnn.setForeground(new java.awt.Color(255, 255, 255));
        makeAnn.setText("Make Announcement");
        makeAnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeAnnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update Info :");

        playerInfoUpdate.setBackground(new java.awt.Color(51, 51, 51));
        playerInfoUpdate.setForeground(new java.awt.Color(255, 255, 255));
        playerInfoUpdate.setText("Player Info Update");
        playerInfoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerInfoUpdateActionPerformed(evt);
            }
        });

        coachInfoUpdate.setBackground(new java.awt.Color(51, 51, 51));
        coachInfoUpdate.setForeground(new java.awt.Color(255, 255, 255));
        coachInfoUpdate.setText("Coach Info Update");
        coachInfoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachInfoUpdateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hire New Members :");

        hireCoach.setBackground(new java.awt.Color(51, 51, 51));
        hireCoach.setForeground(new java.awt.Color(255, 255, 255));
        hireCoach.setText("Hire New Coach");
        hireCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hireCoachActionPerformed(evt);
            }
        });

        hirePlayer.setBackground(new java.awt.Color(51, 51, 51));
        hirePlayer.setForeground(new java.awt.Color(255, 255, 255));
        hirePlayer.setText("Hire New Player");
        hirePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hirePlayerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("   View Finances :");

        viewFinances.setBackground(new java.awt.Color(51, 51, 51));
        viewFinances.setForeground(new java.awt.Color(255, 255, 255));
        viewFinances.setText("View Finances");
        viewFinances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFinancesActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit Program");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   View Members :");

        viewCoach.setBackground(new java.awt.Color(51, 51, 51));
        viewCoach.setForeground(new java.awt.Color(255, 255, 255));
        viewCoach.setText("View Coach(s)");
        viewCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCoachActionPerformed(evt);
            }
        });

        viewPlayers.setBackground(new java.awt.Color(51, 51, 51));
        viewPlayers.setForeground(new java.awt.Color(255, 255, 255));
        viewPlayers.setText("View All Players");
        viewPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPlayersActionPerformed(evt);
            }
        });

        coachRequestButton.setBackground(new java.awt.Color(51, 51, 51));
        coachRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        coachRequestButton.setText("View Coach Requests");
        coachRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachRequestButtonActionPerformed(evt);
            }
        });

        playerRequestButton.setBackground(new java.awt.Color(51, 51, 51));
        playerRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        playerRequestButton.setText("View Player Requests");
        playerRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(coachRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAnn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeAnn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(playerInfoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(coachInfoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(189, 189, 189))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(hirePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(hireCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewFinances, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(301, 301, 301))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(viewPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(viewCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAnn)
                    .addComponent(makeAnn)
                    .addComponent(playerInfoUpdate)
                    .addComponent(coachInfoUpdate))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachRequestButton)
                    .addComponent(playerRequestButton))
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewFinances)
                    .addComponent(hireCoach)
                    .addComponent(hirePlayer)
                    .addComponent(viewCoach)
                    .addComponent(viewPlayers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPlayersActionPerformed
        // TODO add your handling code here:
        List<Player> p = FootballClubManagement.readPlayer();
        ViewAll viewP = new ViewAll();
        viewP.setPlayerInfo(p);
        viewP.show();
    }//GEN-LAST:event_viewPlayersActionPerformed

    private void makeAnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeAnnActionPerformed
        // TODO add your handling code here:
        MakeAnnouncement makeAnn = new MakeAnnouncement();
        makeAnn.show();
    }//GEN-LAST:event_makeAnnActionPerformed

    private void viewAnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnnActionPerformed
        // TODO add your handling code here:
        List<Announcement> ann = FootballClubManagement.readAnnouncements();

        // Create ViewAll instance and set announcements
        ViewAll viewAnn = new ViewAll();
        viewAnn.setAnnouncements(ann);

        // Display the ViewAll window
        viewAnn.show();

    }//GEN-LAST:event_viewAnnActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void viewCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCoachActionPerformed
        // TODO add your handling code here:
        List<Coach> c = FootballClubManagement.readCoach();
        ViewAll viewC = new ViewAll();
        viewC.setCoachInfo(c);
        viewC.show();
    }//GEN-LAST:event_viewCoachActionPerformed

    private void coachRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachRequestButtonActionPerformed
        // TODO add your handling code here:
        FootballClubManagement.readRequests("CoachRequests.txt");
        List<Request> req = FootballClubManagement.coachRequests;
        ViewAll viewCR = new ViewAll();
        viewCR.setCoachRequestInfo(req);
        viewCR.show();

    }//GEN-LAST:event_coachRequestButtonActionPerformed

    private void playerRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerRequestButtonActionPerformed
        // TODO add your handling code here:
        FootballClubManagement.readRequests("PlayerRequests.txt");
        List<Request> req = FootballClubManagement.playerRequests;
        ViewAll viewPR = new ViewAll();
        viewPR.setPlayerRequestInfo(req);
        viewPR.show();
    }//GEN-LAST:event_playerRequestButtonActionPerformed

    private void viewFinancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFinancesActionPerformed
        // TODO add your handling code here:
        FootballClubManagement.readPlayer(); 
        List<Player> players = FootballClubManagement.players;
        String[] playerStrings = new String[players.size()];
        double totalContractMoney = 0;

        for (int i = 0; i < players.size(); i++) {
            Player player = players.get(i);
            playerStrings[i] = player.getPerson().getName() + "\nContract Money: $" + player.getContractMoney();
            totalContractMoney += player.getContractMoney();
            
        }

       

        ViewAll viewFinances = new ViewAll();
        viewFinances.setFinancesInfo(playerStrings, totalContractMoney);
        viewFinances.show();
    }//GEN-LAST:event_viewFinancesActionPerformed

    private void hirePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hirePlayerActionPerformed
        // TODO add your handling code here:
        PlayerRegister playerRegister = new PlayerRegister();
        playerRegister.show();
    }//GEN-LAST:event_hirePlayerActionPerformed

    private void hireCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hireCoachActionPerformed
        // TODO add your handling code here:
        CoachRegister coachRegister = new CoachRegister();
        coachRegister.show();
    }//GEN-LAST:event_hireCoachActionPerformed

    private void playerInfoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerInfoUpdateActionPerformed
        // TODO add your handling code here:
        updatePlayer upP = new updatePlayer();
        upP.show();
    }//GEN-LAST:event_playerInfoUpdateActionPerformed

    private void coachInfoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachInfoUpdateActionPerformed
        // TODO add your handling code here:
        CoachUpdate coachUpdate = new CoachUpdate();
        coachUpdate.show();
    }//GEN-LAST:event_coachInfoUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coachInfoUpdate;
    private javax.swing.JButton coachRequestButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hireCoach;
    private javax.swing.JButton hirePlayer;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton makeAnn;
    private javax.swing.JButton playerInfoUpdate;
    private javax.swing.JButton playerRequestButton;
    private javax.swing.JButton viewAnn;
    private javax.swing.JButton viewCoach;
    private javax.swing.JButton viewFinances;
    private javax.swing.JButton viewPlayers;
    // End of variables declaration//GEN-END:variables
}
