/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package footballclubmanagement;

import java.util.List;

/**
 *
 * @author USER
 */
public class PlayerPage extends javax.swing.JFrame {

    /**
     * Creates new form PlayerPage
     */
    public PlayerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Backdrop = new javax.swing.JPanel();
        viewAnnouncements = new javax.swing.JButton();
        viewOwnInformation = new javax.swing.JButton();
        viewOtherPlayers = new javax.swing.JButton();
        makeRequests = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(255, 255, 0));
        setLocation(new java.awt.Point(400, 100));
        setName(""); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        Backdrop.setBackground(new java.awt.Color(204, 204, 255));

        viewAnnouncements.setBackground(new java.awt.Color(0, 0, 102));
        viewAnnouncements.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewAnnouncements.setForeground(new java.awt.Color(255, 255, 255));
        viewAnnouncements.setText("View  Player Announcements");
        viewAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAnnouncementsActionPerformed(evt);
            }
        });

        viewOwnInformation.setBackground(new java.awt.Color(0, 0, 102));
        viewOwnInformation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewOwnInformation.setForeground(new java.awt.Color(255, 255, 255));
        viewOwnInformation.setText("View Own Information");
        viewOwnInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOwnInformationActionPerformed(evt);
            }
        });

        viewOtherPlayers.setBackground(new java.awt.Color(0, 0, 102));
        viewOtherPlayers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewOtherPlayers.setForeground(new java.awt.Color(255, 255, 255));
        viewOtherPlayers.setText("View Other Players' Information");
        viewOtherPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOtherPlayersActionPerformed(evt);
            }
        });

        makeRequests.setBackground(new java.awt.Color(0, 0, 102));
        makeRequests.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makeRequests.setForeground(new java.awt.Color(255, 255, 255));
        makeRequests.setText("Make requests");
        makeRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeRequestsActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        Title.setBackground(new java.awt.Color(0, 51, 51));
        Title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("PLAYER PAGE");

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/footballclubmanagement/football-player (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        close.setBackground(new java.awt.Color(102, 102, 255));
        close.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Exit");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackdropLayout = new javax.swing.GroupLayout(Backdrop);
        Backdrop.setLayout(BackdropLayout);
        BackdropLayout.setHorizontalGroup(
            BackdropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackdropLayout.createSequentialGroup()
                .addGroup(BackdropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackdropLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(BackdropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewOtherPlayers)
                            .addComponent(viewOwnInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BackdropLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackdropLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        BackdropLayout.setVerticalGroup(
            BackdropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackdropLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(viewAnnouncements)
                .addGap(41, 41, 41)
                .addComponent(viewOwnInformation)
                .addGap(38, 38, 38)
                .addComponent(viewOtherPlayers)
                .addGap(39, 39, 39)
                .addComponent(makeRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(749, Short.MAX_VALUE))
            .addComponent(Backdrop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backdrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAnnouncementsActionPerformed
        // TODO add your handling code here:
        List<Announcement> ann = FootballClubManagement.readAnnouncements();
        ViewAll viewAnn = new ViewAll();
        viewAnn.setAnnouncements(ann);
        viewAnn.show();
                
    }//GEN-LAST:event_viewAnnouncementsActionPerformed

    private void viewOtherPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOtherPlayersActionPerformed
        // TODO add your handling code here:
        List<Player> p = FootballClubManagement.readPlayer();
        ViewAll viewP = new ViewAll();
        viewP.setPlayerLimitedInfo(p);
        viewP.show();
    }//GEN-LAST:event_viewOtherPlayersActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void viewOwnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOwnInformationActionPerformed
        // TODO add your handling code here:
        ViewAll viewPlayer = new ViewAll();
        viewPlayer.setPlayerOwnInfo(FootballClubManagement.loggedInPlayer);
        viewPlayer.show();
    }//GEN-LAST:event_viewOwnInformationActionPerformed

    private void makeRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeRequestsActionPerformed
        // TODO add your handling code here:
        PlayerRequests pr = new PlayerRequests();
        pr.show();
    }//GEN-LAST:event_makeRequestsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backdrop;
    private javax.swing.JLabel Title;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton makeRequests;
    private javax.swing.JButton viewAnnouncements;
    private javax.swing.JButton viewOtherPlayers;
    private javax.swing.JButton viewOwnInformation;
    // End of variables declaration//GEN-END:variables
}
